name: CyberBrowser

options:
  bundleIdPrefix: com.cyberbrowser
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: false

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    CODE_SIGN_IDENTITY: ""
    CODE_SIGNING_REQUIRED: "NO"
    CODE_SIGNING_ALLOWED: "NO"

targets:
  CyberBrowser:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "*.yml"
          - "*.yaml"
          - "*.md"
          - ".git/**"
          - ".gitignore"
          - "project.yml"
          - "codemagic.yaml"
          - "preview/**"
          - "*.bat"
    info:
      path: Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIBackgroundModes:
          - audio
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cyberbrowser.app
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
